server {
    listen 80;
    client_max_body_size 10M;

    location /api/ {
        proxy_pass         https://backend.railway.internal:8000/;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_read_timeout 60s;
    }

    location / {
        proxy_pass       https://frontend.railway.internal:3000;
        proxy_set_header Host $host;
    }
}
